services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
      cluster.name: "docker-cluster"
      discovery.type: single-node
      cluster.routing.allocation.disk.threshold_enabled: "false"
    ports:
      - 9200:9200
    volumes:
      - data01:/usr/share/elasticsearch_data
    networks:
      - elastic
  kib01:
    image: docker.elastic.co/kibana/kibana:7.12.0
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    networks:
      - elastic
  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - 3000:3000
    environment:
      BONSAI_URL: http://elasticsearch:9200
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - db
      - elastic
    depends_on:
      - db
      - elasticsearch

volumes:
  data01:
    driver: local

networks:
  db:
    driver: bridge
  elastic:
    driver: bridge
