version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-node-browsers
        environment:
          RAILS_ENV: development
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
  test:
    docker:
      - image: circleci/ruby:2.6.6-node-browsers
        environment:
          BUNDLE_JOBS: '3'
          BUNDLE_RETRY: '3'
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          RAILS_ENV: test
          TEST_DB: circle_test
      - image: circleci/postgres:13.1
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
        environment:
          cluster.name: transbucket-test
          xpack.security.enabled: false
          transport.host: localhost
          network.host: 127.0.0.1
          http.port: 9200
          discovery.type: single-node
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Wait for elasticsearch
          command: dockerize -wait tcp://localhost:9200 -timeout 1m
      - run:
          name: Lift elasticsearch disk watermark restrictions
          command: |
            curl -XPUT -H "Content-Type: application/json" http://localhost:9200/_cluster/settings -d '{ "transient": { "cluster.routing.allocation.disk.threshold_enabled": false } }'
      - run: bundle exec rake db:create db:migrate
      - run: bundle exec rspec || bundle exec rspec --only-failures || bundle exec rspec --only-failures

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test:
        requires:
          - build
