require File.expand_path('../boot', __FILE__)

require 'rails/all'

if RUBY_VERSION >= '3.0'
  # Rails 4.2's Fanout#subscribe relies on `Proc.new` implicitly capturing
  # the caller's block, which Ruby 3 no longer supports. Railties (e.g.
  # rack-mini-profiler) call ActiveSupport::Notifications.subscribe during
  # initialization, before config/initializers load, so this must be patched
  # here rather than in an initializer.
  class ActiveSupport::Notifications::Fanout
    def subscribe(pattern = nil, callable = nil, &block)
      subscriber = Subscribers.new pattern, (callable || block)
      synchronize do
        @subscribers << subscriber
        @listeners_for.clear
      end
      subscriber
    end
  end

  # ActiveRecord::Type.add_modifier is generated by ActiveSupport's `delegate`
  # macro, which (in this Rails 5.2 vintage) forwards a trailing options hash
  # as a positional argument instead of as **kwargs under Ruby 3's
  # keyword-argument separation. postgresql_adapter.rb calls it with a
  # keyword arg (`adapter: :postgresql`) as soon as it's required, which
  # happens lazily during Rails.application.initialize! -- after this file
  # has already loaded and redefined it here.
  module ActiveRecord::Type
    class << self
      def add_modifier(options, klass, **args)
        registry.add_modifier(options, klass, **args)
      end
    end
  end

  # ActiveModel::Type::Integer#initialize(*); super; end captures a trailing
  # keyword arg (postgresql_adapter.rb calls Type::Integer.new(limit: 2)) into
  # its bare splat as a positional Hash, then loses its keyword-ness when
  # forwarded via bare `super` to Value#initialize(precision:, limit:, scale:)
  # under Ruby 3. ruby2_keywords is Ruby's own fix for exactly this shape of
  # pre-2.7 splat-forwarding method. Needed this early for the same reason as
  # add_modifier above: it's the same postgresql_adapter.rb type map setup,
  # hit during Rails.application.initialize! before initializers load.
  ActiveModel::Type::Integer.send(:ruby2_keywords, :initialize)

  # ActiveRecord::ConnectionAdapters::PostgreSQL::OID::SpecializedString#initialize
  # calls `super(options)` -- a positional Hash, even when empty -- against
  # Value#initialize(precision:, limit:, scale:), which takes no positional
  # args at all. Ruby <3.0 silently coerced a trailing Hash into keywords for
  # a call like this; Ruby 3 doesn't. Same early postgresql_adapter.rb type
  # map setup as the two patches above.
  require 'active_record/connection_adapters/postgresql/oid/specialized_string'
  class ActiveRecord::ConnectionAdapters::PostgreSQL::OID::SpecializedString
    def initialize(type, **options)
      @type = type
      super(**options)
    end
  end

  # ActiveRecord::ConnectionAdapters::RealTransaction/SavepointTransaction#
  # initialize both end in a bare `*args` and a bare `super`, exactly like
  # ActiveModel::Type::Integer above -- TransactionManager#begin_transaction
  # always calls them with a trailing `run_commit_callbacks:` keyword, which
  # loses its keyword-ness across that round trip under Ruby 3.
  ActiveRecord::ConnectionAdapters::RealTransaction.send(:ruby2_keywords, :initialize)
  ActiveRecord::ConnectionAdapters::SavepointTransaction.send(:ruby2_keywords, :initialize)

  # Same positional-Hash-into-a-kwargs-only-method bug as SpecializedString,
  # but on the hottest possible path: every single save/create/update/destroy
  # goes through Transactions::ClassMethods#transaction and/or the instance
  # #transaction below, both of which pass their `options = {}` default
  # positionally into DatabaseStatements#transaction(requires_new:,
  # isolation:, joinable:) -- a keyword-only method.
  module ActiveRecord::Transactions::ClassMethods
    def transaction(**options, &block)
      connection.transaction(**options, &block)
    end
  end

  module ActiveRecord::Transactions
    def transaction(**options, &block)
      self.class.transaction(**options, &block)
    end
  end

  # ActiveRecord::Delegation::ClassMethods#create(klass, *args) is the same
  # bare-splat-then-forward shape as ActiveModel::Type::Integer above. Every
  # relation-spawning call (.only, .except, .where, uniqueness validation's
  # #exists?, etc.) routes through Relation.create(klass, values: values),
  # which loses the values: keyword across this forwarding under Ruby 3.
  ActiveRecord::Delegation::ClassMethods.send(:ruby2_keywords, :create)

  # ActiveSupport::Cache::Store#write and #fetch_multi both call
  # `Entry.new(value, options.merge(...))` -- an explicit positional Hash --
  # against Entry#initialize(value, compress:, compress_threshold:, version:,
  # expires_in:, **), which takes only 1 positional arg. Unlike the
  # ruby2_keywords cases above, this is an explicit Hash literal at the call
  # site, not a forwarded splat, so ruby2_keywords doesn't apply; overriding
  # the constructor to accept a legacy positional options Hash and re-thread
  # it as real keywords does. Every Rails.cache.write/fetch call hits this.
  class ActiveSupport::Cache::Entry
    def self.new(value, options = {}, **keywords)
      entry = allocate
      entry.send(:initialize, value, **options, **keywords)
      entry
    end
  end

  # ActionView's cache helper passes its cache options as a positional Hash to
  # cache_fragment_name, while Rails 5.2 defines that method with keyword-only
  # options. Ruby 2.7 accepted this call; Ruby 3 raises before the view can
  # render whenever fragment caching is enabled.
  module ActionView::Helpers::CacheHelper
    def cache_fragment_name(name = {}, options = nil, skip_digest: nil, virtual_path: nil)
      options ||= {}
      skip_digest = options[:skip_digest] if options.key?(:skip_digest)
      virtual_path = options[:virtual_path] if options.key?(:virtual_path)

      if skip_digest
        name
      else
        fragment_name_with_digest(name, virtual_path)
      end
    end
  end

  # ActionView::ViewPaths delegates template_exists?/any_templates? to
  # lookup_context via ActiveSupport's `delegate` -- the same broken-splat
  # shape as ActiveRecord::Type.add_modifier above. ImplicitRender#default_render
  # calls `template_exists?(name, prefixes, variants: request.variant)`; once
  # that keyword loses its keyword-ness across the delegate, it lands in the
  # *positional* `partial` slot of LookupContext#exists?(name, prefixes=[],
  # partial=false, keys=[], **options), silently switching the lookup into
  # partial-template mode (which looks for "_index", not "index") and always
  # failing to find the real template -- raising UnknownFormat on every
  # implicit render (any bare `respond_to do |format| format.html end` with
  # no explicit render included).
  ActionView::ViewPaths.send(:ruby2_keywords, :template_exists?)
  ActionView::ViewPaths.send(:ruby2_keywords, :any_templates?)

  # Same explicit-positional-Hash-into-a-kwargs-only-method bug as
  # SpecializedString/Cache::Entry above, this time on every single signed
  # cookie write (session cookie included): EncryptedKeyRotatingCookieJar#
  # commit passes `expiry_options(options)` positionally to
  # MessageEncryptor#encrypt_and_sign(value, expires_at:, expires_in:,
  # purpose:), a kwargs-only method.
  class ActionDispatch::Cookies::EncryptedKeyRotatingCookieJar
    private

    def commit(options)
      options[:value] = @encryptor.encrypt_and_sign(serialize(options[:value]), **expiry_options(options))

      raise ActionDispatch::Cookies::CookieOverflow if options[:value].bytesize > ActionDispatch::Cookies::MAX_COOKIE_SIZE
    end
  end

  # One more link in the same chain: MessageEncryptor#_encrypt itself passes
  # its own **metadata_options positionally into Metadata.wrap(message,
  # expires_at:, expires_in:, purpose:) instead of re-splatting them.
  class ActiveSupport::MessageEncryptor
    def _encrypt(value, **metadata_options)
      cipher = new_cipher
      cipher.encrypt
      cipher.key = @secret

      iv = cipher.random_iv
      cipher.auth_data = "" if aead_mode?

      encrypted_data = cipher.update(ActiveSupport::Messages::Metadata.wrap(@serializer.dump(value), **metadata_options))
      encrypted_data << cipher.final

      blob = "#{::Base64.strict_encode64 encrypted_data}--#{::Base64.strict_encode64 iv}"
      blob = "#{blob}--#{::Base64.strict_encode64 cipher.auth_tag}" if aead_mode?
      blob
    end
  end

  # ActionDispatch::Integration::Runner#get/post/etc (used by request specs)
  # are defined via `define_method(method) do |*args| ... end` -- a bare
  # splat with no **kwargs -- then forwarded with `integration_session.
  # __send__(method, *args)`. A trailing `params: {...}` keyword from the
  # spec loses its keyword-ness across that splat-and-resend, landing as a
  # second positional argument on RequestHelpers#get(path, **args), which
  # only takes one. ruby2_keywords restores correct forwarding.
  %w(get post patch put head delete cookies assigns follow_redirect!).each do |verb|
    ActionDispatch::Integration::Runner.send(:ruby2_keywords, verb)
  end
end

# https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-rails#activesupport-instrumentation
require 'elasticsearch/rails/instrumentation'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module Transbucket
  class Application < Rails::Application
    # TODO include blocking ips for bad users
    # config.middleware.use Rack::Attack

    config.action_controller.page_cache_directory = "#{Rails.root.to_s}/public/page_cache"

    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.

    # Set Time.zone default to the specified zone and make Active Record auto-convert to this zone.
    # Run "rake -D time" for a list of tasks for finding time zone names. Default is UTC.
    # config.time_zone = 'Central Time (US & Canada)'

    # The default locale is :en and all translations from config/locales/*.rb,yml are auto loaded.
    # config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}').to_s]
    config.i18n.default_locale = :en
    config.i18n.fallbacks = true
    # Rails' ruby schema dumper can't represent expression indexes (the
    # lower(username)/lower(email) functional indexes the login-lookup fix
    # depends on), so a plain `rake db:migrate` silently drops them from
    # schema.rb -- bit us twice in one night. structure.sql is generated via
    # pg_dump instead, which captures the database at the SQL level and
    # doesn't have this gap.
    config.active_record.schema_format = :sql

    # necessary for using bower-rails!
    config.assets.paths << Rails.root.join('vendor', 'assets', 'bower_components')
    config.assets.paths << Rails.root.join('vendor', 'assets', 'bower_components', 'jquery-ui', 'themes', 'smoothness', 'images')
    config.assets.paths << Rails.root.join('vendor', 'assets', 'bower_components', 'tinymce', 'skins', 'lightgray', 'img')
    config.assets.paths << Rails.root.join('vendor', 'assets', 'bower_components', 'tinymce', 'skins', 'lightgray', 'fonts')
    config.assets.precompile << 'tinymce/langs/*.js'

    config.generators do |g|
      g.test_framework :rspec,
        :fixtures => false,
        :view_specs => false,
        :helper_specs => false,
        :routing_specs => false,
        :controller_specs => true,
        :request_specs => true
    end
  end
end
