# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

defaults: &defaults
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5
  username: Alex
  password:
  morphology: stem_en
  enable_star: true
  min_infix_len: 3

development:
  <<: *defaults
  database: psql_development
  #socket: /tmp/mysql.sock
  #socket: /Applications/XAMPP/xamppfiles/var/mysql/mysql.sock
  #port: 9306

test:
  <<: *defaults
  database: psql_test

production:
  <<: *defaults
  database: psql_production

local:
  <<: *defaults
  database: psql_local