class CreateContentEvents < ActiveRecord::Migration[4.2]
  def change
    create_table :content_events do |t|
      t.integer :user_id
      # These are one-way HMACs generated by the application. Do not store
      # raw IP addresses, user agents, or browser identifiers in this table.
      t.string :visitor_hash, limit: 64
      t.string :network_hash, limit: 64
      t.string :content_type, null: false
      t.integer :content_id, null: false
      t.string :event_type, null: false
      t.string :source, null: false, default: 'server'
      t.string :locale, limit: 10
      t.datetime :occurred_at, null: false
    end

    add_index :content_events, [:content_type, :content_id, :event_type, :occurred_at], name: 'index_content_events_on_content_event_time'
    add_index :content_events, [:user_id, :occurred_at]
    add_index :content_events, [:visitor_hash, :occurred_at]
    add_index :content_events, [:network_hash, :occurred_at]
  end
end
